<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.18">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>SOC2069 | 2026</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<link href="../../site_pics/logo_name_white.jpg" rel="icon" type="image/jpeg">
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-64a204ab8560d761af7679ceaba22944.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-1e062f3de27d5a13a642256a90a2a83c.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<link href="../../site_libs/quarto-contrib/fontawesome6-0.1.0/all.css" rel="stylesheet">
<link href="../../site_libs/quarto-contrib/fontawesome6-0.1.0/latex-fontsize.css" rel="stylesheet">
<script src="../../site_libs/quarto-contrib/iconify-2.1.0/iconify-icon.min.js"></script>
<script id="quarto-search-options" type="application/json">{
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


<link rel="stylesheet" href="../labcss.css">
</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title"><strong>SOC2069</strong> <i class="fa-solid fa-chart-line" aria-label="chart-line"></i> Quantitative Methods</span>
    </a>
  </div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../Materials/index.html"> 
<span class="menu-text">Materials</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../Data/index.html"> 
<span class="menu-text">Data</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="https://ncl.instructure.com/courses/73213" target="_blank"> 
<span class="menu-text"><iconify-icon role="img" inline="" icon="arcticons:canvasstudent" style="font-size: l;" aria-label="Icon canvasstudent from arcticons Iconify.design set." title="Icon canvasstudent from arcticons Iconify.design set."></iconify-icon> Canvas</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-full page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#interpretation-guide-saying-what-your-results-mean" id="toc-interpretation-guide-saying-what-your-results-mean" class="nav-link active" data-scroll-target="#interpretation-guide-saying-what-your-results-mean">Interpretation Guide: Saying What Your Results Mean</a>
  <ul class="collapse">
  <li><a href="#describing-one-variable" id="toc-describing-one-variable" class="nav-link" data-scroll-target="#describing-one-variable">1. Describing one variable</a></li>
  <li><a href="#two-categorical-variables-contingency-tables" id="toc-two-categorical-variables-contingency-tables" class="nav-link" data-scroll-target="#two-categorical-variables-contingency-tables">2. Two categorical variables: contingency tables</a></li>
  <li><a href="#a-scale-variable-across-groups" id="toc-a-scale-variable-across-groups" class="nav-link" data-scroll-target="#a-scale-variable-across-groups">3. A scale variable across groups</a></li>
  <li><a href="#two-scale-variables-correlation" id="toc-two-scale-variables-correlation" class="nav-link" data-scroll-target="#two-scale-variables-correlation">4. Two scale variables: correlation</a></li>
  <li><a href="#simple-linear-regression" id="toc-simple-linear-regression" class="nav-link" data-scroll-target="#simple-linear-regression">5. Simple linear regression</a></li>
  <li><a href="#multiple-linear-regression" id="toc-multiple-linear-regression" class="nav-link" data-scroll-target="#multiple-linear-regression">6. Multiple linear regression</a></li>
  <li><a href="#a-categorical-predictor" id="toc-a-categorical-predictor" class="nav-link" data-scroll-target="#a-categorical-predictor">7. A categorical predictor</a></li>
  <li><a href="#logistic-regression" id="toc-logistic-regression" class="nav-link" data-scroll-target="#logistic-regression">8. Logistic regression</a></li>
  <li><a href="#uncertainty-confidence-intervals-and-p-values" id="toc-uncertainty-confidence-intervals-and-p-values" class="nav-link" data-scroll-target="#uncertainty-confidence-intervals-and-p-values">9. Uncertainty: confidence intervals and p-values</a></li>
  <li><a href="#reporting-checklist" id="toc-reporting-checklist" class="nav-link" data-scroll-target="#reporting-checklist">Reporting checklist</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content column-page-left" id="quarto-document-content"><header id="title-block-header" class="quarto-title-block"></header>




<section id="interpretation-guide-saying-what-your-results-mean" class="level1">
<h1>Interpretation Guide: Saying What Your Results Mean</h1>
<p>For each kind of output you will meet in this module, this guide gives:</p>
<ul>
<li>what to look at in the JASP output,</li>
<li>a <strong>model write-up</strong> you can adapt for your own report, and</li>
<li>common phrasings to <strong>avoid</strong>, with better alternatives.</li>
</ul>
<p>All the examples use the course datasets, so you can reproduce every number yourself.</p>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Important</span>Three rules for every write-up
</div>
</div>
<div class="callout-body-container callout-body">
<ol type="1">
<li><strong>Say what was measured</strong>: name the survey, year, question and scale, not just the variable name.</li>
<li><strong>Give direction <em>and</em> size</strong>: “higher” is not enough. Say how much higher, in units a reader understands.</li>
<li><strong>Describe associations, not causes</strong>: regression on survey data shows how variables go together. Use “is associated with”, “is higher among”, “predicts”, not “causes”, “increases”, “leads to” or “the effect of”.</li>
</ol>
</div>
</div>
<section id="describing-one-variable" class="level2">
<h2 class="anchored" data-anchor-id="describing-one-variable">1. Describing one variable</h2>
<p><strong>Example</strong>: social trust (<code>ppltrst</code>, 0-10) in the UK sample of the European Social Survey, Round 11 (<code>gb-ess11-trust.sav</code>).</p>
<p><strong>Look at</strong>: valid N, mean, median, mode, standard deviation, and the distribution plot.</p>
<blockquote class="blockquote">
<p>In the UK sample of the European Social Survey (2023-24, n = 1,680), respondents rated how far most people can be trusted at 5.4 on average on a scale from 0 (“you can’t be too careful”) to 10 (“most people can be trusted”) (SD = 2.3). The median was 6 and the most common answer 7, so more respondents leaned towards trust than away from it, with a smaller tail of very low scores pulling the mean slightly below the median.</p>
</blockquote>
<table class="caption-top table">
<colgroup>
<col style="width: 35%">
<col style="width: 65%">
</colgroup>
<thead>
<tr class="header">
<th>✗ Avoid</th>
<th>✓ Better</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>“The mean of ppltrst is 5.4.”</td>
<td>Name the concept and the scale: “average trust was 5.4 on a 0-10 scale”.</td>
</tr>
<tr class="even">
<td>“Most people trust others.”</td>
<td>Say what the numbers show: “the most common answer was 7 out of 10”.</td>
</tr>
<tr class="odd">
<td>Reporting the mean of a nominal variable</td>
<td>Use percentages and the mode for categorical variables.</td>
</tr>
</tbody>
</table>
</section>
<section id="two-categorical-variables-contingency-tables" class="level2">
<h2 class="anchored" data-anchor-id="two-categorical-variables-contingency-tables">2. Two categorical variables: contingency tables</h2>
<p><strong>Example</strong>: <code>SocTrust</code> by sex, British Social Attitudes 2010 (column percentages).</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th></th>
<th style="text-align: right;">Men</th>
<th style="text-align: right;">Women</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Most people can be trusted</td>
<td style="text-align: right;">51.4%</td>
<td style="text-align: right;">40.7%</td>
</tr>
<tr class="even">
<td>Can’t be too careful</td>
<td style="text-align: right;">48.6%</td>
<td style="text-align: right;">59.3%</td>
</tr>
<tr class="odd">
<td>n</td>
<td style="text-align: right;">461</td>
<td style="text-align: right;">599</td>
</tr>
</tbody>
</table>
<p><strong>Look at</strong>: percentages <em>within</em> each category of the predictor (column percentages if the predictor is in the columns), and the size of the difference.</p>
<blockquote class="blockquote">
<p>In the 2010 British Social Attitudes survey, men were more likely than women to say that most people can be trusted (51% vs 41%), a difference of about 11 percentage points.</p>
</blockquote>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 66%">
</colgroup>
<thead>
<tr class="header">
<th>✗ Avoid</th>
<th>✓ Better</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>“237 men and 244 women trust people.”</td>
<td>Compare percentages, not counts: the groups are different sizes.</td>
</tr>
<tr class="even">
<td>“Women are 11% less trusting.”</td>
<td>“11 <strong>percentage points</strong> lower” (40.7% is about 21% lower <em>than</em> 51.4%: not the same thing).</td>
</tr>
<tr class="odd">
<td>Using row percentages to compare men and women</td>
<td>Percentages must add to 100 <em>within</em> each group you compare.</td>
</tr>
</tbody>
</table>
</section>
<section id="a-scale-variable-across-groups" class="level2">
<h2 class="anchored" data-anchor-id="a-scale-variable-across-groups">3. A scale variable across groups</h2>
<p><strong>Example</strong>: <code>ppltrst</code> (0-10) by gender, ESS Round 11, UK.</p>
<p><strong>Look at</strong>: the mean or median in each group, the spread, and the box plot.</p>
<blockquote class="blockquote">
<p>Men in the UK ESS sample reported slightly higher trust than women (mean 5.5 vs 5.3 on the 0-10 scale; medians 6 and 5). The distributions overlap heavily: the gap between the group means is small compared with the spread within each group (SD of about 2.3 points).</p>
</blockquote>
</section>
<section id="two-scale-variables-correlation" class="level2">
<h2 class="anchored" data-anchor-id="two-scale-variables-correlation">4. Two scale variables: correlation</h2>
<p><strong>Example</strong>: income inequality and social trust across 23 rich countries (<code>pickett2009</code>).</p>
<p><strong>Look at</strong>: the scatter plot first, then Pearson’s <em>r</em> (direction and strength).</p>
<blockquote class="blockquote">
<p>Across 23 economically developed countries, income inequality and social trust were strongly negatively correlated (r = −0.66): in more unequal countries, a smaller share of people said that most people can be trusted.</p>
</blockquote>
<table class="caption-top table">
<colgroup>
<col style="width: 38%">
<col style="width: 61%">
</colgroup>
<thead>
<tr class="header">
<th>✗ Avoid</th>
<th>✓ Better</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>“Inequality reduces trust.”</td>
<td>“Inequality is negatively associated with trust.”</td>
</tr>
<tr class="even">
<td>“Unequal countries have untrusting citizens.”</td>
<td>The data are country-level: they describe countries, not individuals (the ecological fallacy).</td>
</tr>
<tr class="odd">
<td>“r = −0.66, so 66% of trust is explained.”</td>
<td>The share of variance explained is r² ≈ 0.44.</td>
</tr>
</tbody>
</table>
</section>
<section id="simple-linear-regression" class="level2">
<h2 class="anchored" data-anchor-id="simple-linear-regression">5. Simple linear regression</h2>
<p><strong>Example</strong>: <code>Trust</code> (% trusting) regressed on <code>Income inequality</code> (income quintile share ratio), <code>pickett2009</code>.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>(n = 23)</th>
<th style="text-align: right;">Unstandardized</th>
<th style="text-align: right;">R²</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>(Intercept)</td>
<td style="text-align: right;">77.06</td>
<td style="text-align: right;">0.441</td>
</tr>
<tr class="even">
<td>Income inequality</td>
<td style="text-align: right;">−6.54</td>
<td style="text-align: right;"></td>
</tr>
</tbody>
</table>
<p><strong>Look at</strong>: the <strong>Unstandardized</strong> coefficient of the predictor, in the units of both variables; R².</p>
<blockquote class="blockquote">
<p>A simple linear regression shows that countries with higher income inequality tend to have lower social trust: each one-unit higher income quintile share ratio (for example, the richest fifth earning 8 rather than 7 times as much as the poorest fifth) is associated with a share of trusting people that is about 6.5 percentage points lower. Income inequality alone accounts for 44% of the variation in trust across these countries (R² = 0.44).</p>
</blockquote>
<p>The intercept (77.06) is the predicted trust when inequality is 0, which is impossible (the ratio cannot be below 1), so it does not need interpreting.</p>
</section>
<section id="multiple-linear-regression" class="level2">
<h2 class="anchored" data-anchor-id="multiple-linear-regression">6. Multiple linear regression</h2>
<p><strong>Example</strong>: the same model, adding <code>Homicides</code> (per 100,000 population).</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>(n = 23)</th>
<th style="text-align: right;">Unstandardized</th>
<th>95% CI</th>
<th style="text-align: right;">p</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Income inequality</td>
<td style="text-align: right;">−7.15</td>
<td>−10.98 to −3.32</td>
<td style="text-align: right;">&lt; .001</td>
</tr>
<tr class="even">
<td>Homicides</td>
<td style="text-align: right;">0.17</td>
<td>−0.33 to 0.68</td>
<td style="text-align: right;">.483</td>
</tr>
<tr class="odd">
<td>R²</td>
<td style="text-align: right;">0.455</td>
<td></td>
<td style="text-align: right;"></td>
</tr>
</tbody>
</table>
<p><strong>Look at</strong>: how the main coefficient changes once controls are added; each coefficient’s CI and p-value; R².</p>
<blockquote class="blockquote">
<p>Adjusting for homicide rates, income inequality remained negatively associated with trust: among countries with similar homicide rates, a one-unit higher quintile share ratio was associated with about 7 percentage points lower trust (95% CI −11.0 to −3.3; p &lt; .001). Homicide rates were not reliably associated with trust once inequality was taken into account (b = 0.17, 95% CI −0.33 to 0.68; p = .48), and adding them improved the model’s explanatory power only marginally (R² from 0.44 to 0.46).</p>
</blockquote>
<table class="caption-top table">
<colgroup>
<col style="width: 37%">
<col style="width: 62%">
</colgroup>
<thead>
<tr class="header">
<th>✗ Avoid</th>
<th>✓ Better</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>“Controlling for homicides, inequality’s effect is −7.15.”</td>
<td>“Adjusting for homicide rates, inequality is associated with …” (no “effect”)</td>
</tr>
<tr class="even">
<td>“Homicides increase trust (b = 0.17).”</td>
<td>The CI includes 0 and p = .48: the data cannot tell the direction of this association.</td>
</tr>
<tr class="odd">
<td>“Inequality matters more because −7.15 &gt; 0.17.”</td>
<td>The variables have different units: compare <strong>standardized</strong> coefficients for relative strength.</td>
</tr>
</tbody>
</table>
</section>
<section id="a-categorical-predictor" class="level2">
<h2 class="anchored" data-anchor-id="a-categorical-predictor">7. A categorical predictor</h2>
<p><strong>Example</strong>: trust (0-10) regressed on age group (16-24 vs 25+, reference = 25+) and sex, Community Life Survey 2023-24 (England).</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>(n = 50,706)</th>
<th style="text-align: right;">Unstandardized</th>
<th>95% CI</th>
<th style="text-align: right;">p</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Age group (16-24)</td>
<td style="text-align: right;">−0.59</td>
<td>−0.65 to −0.53</td>
<td style="text-align: right;">&lt; .001</td>
</tr>
<tr class="even">
<td>Sex (Male)</td>
<td style="text-align: right;">−0.01</td>
<td>−0.05 to 0.02</td>
<td style="text-align: right;">.460</td>
</tr>
</tbody>
</table>
<p><strong>Look at</strong>: which category is the <strong>reference</strong>; each coefficient is a difference from it.</p>
<blockquote class="blockquote">
<p>Adults aged 16-24 rated their trust in most people 0.6 points lower on the 0-10 scale than those aged 25 and over, holding sex constant (95% CI −0.65 to −0.53; p &lt; .001). There was no meaningful difference between men and women.</p>
</blockquote>
</section>
<section id="logistic-regression" class="level2">
<h2 class="anchored" data-anchor-id="logistic-regression">8. Logistic regression</h2>
<p><strong>Example</strong>: <code>SocTrust</code> (1 = “Most people can be trusted”) regressed on age and sex, British Social Attitudes 2010.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 14%">
<col style="width: 16%">
<col style="width: 22%">
<col style="width: 12%">
</colgroup>
<thead>
<tr class="header">
<th>(n = 1,060)</th>
<th style="text-align: right;">Estimate</th>
<th style="text-align: right;">Odds ratio</th>
<th>95% CI (OR)</th>
<th style="text-align: right;">p</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Age (years)</td>
<td style="text-align: right;">0.006</td>
<td style="text-align: right;">1.006</td>
<td>0.9995 to 1.013</td>
<td style="text-align: right;">.069</td>
</tr>
<tr class="even">
<td>Sex (Female)</td>
<td style="text-align: right;">−0.437</td>
<td style="text-align: right;">0.646</td>
<td>0.505 to 0.825</td>
<td style="text-align: right;">&lt; .001</td>
</tr>
<tr class="odd">
<td>Nagelkerke R²</td>
<td style="text-align: right;">0.019</td>
<td style="text-align: right;"></td>
<td></td>
<td style="text-align: right;"></td>
</tr>
</tbody>
</table>
<p><strong>Look at</strong>: which outcome category is coded 1; the <strong>Odds Ratio</strong> column; then translate into predicted probabilities (conditional estimates plot).</p>
<blockquote class="blockquote">
<p>A logistic regression shows that, among respondents of the same age, women had about 35% lower odds than men of saying that most people can be trusted (OR = 0.65, 95% CI 0.51 to 0.83; p &lt; .001). In probability terms, the model predicts that 50% of 40-year-old men but 39% of 40-year-old women say most people can be trusted, a gap of about 11 percentage points that is similar at every age. Older respondents were slightly more trusting (about 0.6% higher odds per year of age, or 6% per decade), but this association was not statistically significant (95% CI 0.9995 to 1.013, which JASP rounds to 1.000; p = .069). Age and sex together explain very little of the variation in trust (Nagelkerke R² = 0.02).</p>
</blockquote>
<table class="caption-top table">
<colgroup>
<col style="width: 38%">
<col style="width: 61%">
</colgroup>
<thead>
<tr class="header">
<th>✗ Avoid</th>
<th>✓ Better</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>“Women are 35% less likely to trust.”</td>
<td>“Women’s <strong>odds</strong> of trusting are 35% lower”, and give the probability gap (11 points).</td>
</tr>
<tr class="even">
<td>“The odds ratio is 0.646, so women’s probability is 0.646.”</td>
<td>Odds ratios compare odds, not probabilities.</td>
</tr>
<tr class="odd">
<td>Interpreting the log-odds Estimate directly as a size</td>
<td>Use the sign of the Estimate for direction; use the odds ratio or probabilities for size.</td>
</tr>
<tr class="even">
<td>Not saying which category is coded 1</td>
<td>“The outcome is coded 1 for ‘most people can be trusted’.”</td>
</tr>
</tbody>
</table>
</section>
<section id="uncertainty-confidence-intervals-and-p-values" class="level2">
<h2 class="anchored" data-anchor-id="uncertainty-confidence-intervals-and-p-values">9. Uncertainty: confidence intervals and p-values</h2>
<p><strong>Look at</strong>: the <strong>95% CI</strong> (the range of population values compatible with the data) and the <strong>p-value</strong> (how surprising the estimate would be if the true association were zero).</p>
<blockquote class="blockquote">
<p>The odds of trusting were 35% lower for women (OR = 0.65, 95% CI 0.51 to 0.83; p &lt; .001). Because the interval lies entirely below 1, the data are not compatible with the absence of a sex difference in the population.</p>
</blockquote>
<p><strong>A non-significant result is not evidence of no difference.</strong> In the British Social Attitudes 2024, 16-24-year-olds scored 0.16 points lower than older adults on the 0-10 trust scale (95% CI −0.71 to 0.40; p = .58), based on only 78 young respondents.</p>
<blockquote class="blockquote">
<p>The BSA 2024 shows a small difference in the same direction that is not statistically significant. Its confidence interval is wide and includes both no difference and the 0.6-point gap found in the much larger Community Life Survey, so the BSA 2024 cannot settle whether young people’s trust is lower.</p>
</blockquote>
<table class="caption-top table">
<colgroup>
<col style="width: 39%">
<col style="width: 60%">
</colgroup>
<thead>
<tr class="header">
<th>✗ Avoid</th>
<th>✓ Better</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>“p = .58, so there is no difference.”</td>
<td>“The difference is not statistically significant; the interval is compatible with no difference and with a sizeable one.”</td>
</tr>
<tr class="even">
<td>“p &lt; .001, so the effect is large.”</td>
<td>Significance is about precision, not size: report the coefficient and its interval.</td>
</tr>
<tr class="odd">
<td>“There is a 95% probability that the true value is in the CI.”</td>
<td>“Intervals built this way capture the true value in 95% of repeated samples.”</td>
</tr>
<tr class="even">
<td>“p = 0.000”</td>
<td>Report “p &lt; .001”.</td>
</tr>
</tbody>
</table>
</section>
<section id="reporting-checklist" class="level2">
<h2 class="anchored" data-anchor-id="reporting-checklist">Reporting checklist</h2>
<p>Before you submit, check that each model you report states:</p>
<ul class="task-list">
<li><label><input type="checkbox">the data source, year, population and sample size (n)</label></li>
<li><label><input type="checkbox">how the outcome was measured and coded (for logistic regression: which category is 1)</label></li>
<li><label><input type="checkbox">any recoding decisions (missing values, collapsed categories, cut-points) and why</label></li>
<li><label><input type="checkbox">the reference category of every categorical predictor</label></li>
<li><label><input type="checkbox">the direction <strong>and</strong> size of each key association, in meaningful units</label></li>
<li><label><input type="checkbox">a 95% CI and/or p-value for each key estimate</label></li>
<li><label><input type="checkbox">a measure of model fit (R² or a pseudo-R²)</label></li>
<li><label><input type="checkbox">associational, not causal, language</label></li>
<li><label><input type="checkbox">limitations: measurement, sample (coverage, size, weights) and design (cross-sectional data)</label></li>
</ul>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
            // target, if specified
            link.setAttribute("target", "_blank");
            if (link.getAttribute("rel") === null) {
              link.setAttribute("rel", "noopener");
            }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>