<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.18">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>SOC2069 | 2026</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<link href="../../site_pics/logo_name_white.jpg" rel="icon" type="image/jpeg">
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-64a204ab8560d761af7679ceaba22944.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-1e062f3de27d5a13a642256a90a2a83c.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<link href="../../site_libs/quarto-contrib/fontawesome6-0.1.0/all.css" rel="stylesheet">
<link href="../../site_libs/quarto-contrib/fontawesome6-0.1.0/latex-fontsize.css" rel="stylesheet">
<script src="../../site_libs/quarto-contrib/iconify-2.1.0/iconify-icon.min.js"></script>
<script src="../../site_libs/quarto-contrib/glightbox/glightbox.min.js"></script>
<link href="../../site_libs/quarto-contrib/glightbox/glightbox.min.css" rel="stylesheet">
<link href="../../site_libs/quarto-contrib/glightbox/lightbox.css" rel="stylesheet">
<script id="quarto-search-options" type="application/json">{
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@4/tex-chtml.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../labcss.css">
</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title"><strong>SOC2069</strong> <i class="fa-solid fa-chart-line" aria-label="chart-line"></i> Quantitative Methods</span>
    </a>
  </div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../Materials/index.html"> 
<span class="menu-text">Materials</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../Data/index.html"> 
<span class="menu-text">Data</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="https://ncl.instructure.com/courses/73213" target="_blank"> 
<span class="menu-text"><iconify-icon role="img" inline="" icon="arcticons:canvasstudent" style="font-size: l;" aria-label="Icon canvasstudent from arcticons Iconify.design set." title="Icon canvasstudent from arcticons Iconify.design set."></iconify-icon> Canvas</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-full page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#workshop-2-worksheet" id="toc-workshop-2-worksheet" class="nav-link active" data-scroll-target="#workshop-2-worksheet">Workshop 2 Worksheet</a>
  <ul class="collapse">
  <li><a href="#learning-outcomes" id="toc-learning-outcomes" class="nav-link" data-scroll-target="#learning-outcomes">Learning outcomes</a></li>
  <li><a href="#intro" id="toc-intro" class="nav-link" data-scroll-target="#intro">Intro</a></li>
  <li><a href="#exercise-0-your-module-data-and-analysis-folder" id="toc-exercise-0-your-module-data-and-analysis-folder" class="nav-link" data-scroll-target="#exercise-0-your-module-data-and-analysis-folder">Exercise 0: Your module data and analysis folder</a></li>
  <li><a href="#exercise-1-does-trust-vary-by-sex" id="toc-exercise-1-does-trust-vary-by-sex" class="nav-link" data-scroll-target="#exercise-1-does-trust-vary-by-sex">Exercise 1: Does <em>trust</em> vary by <em>sex</em>?</a>
  <ul class="collapse">
  <li><a href="#contingency-tables" id="toc-contingency-tables" class="nav-link" data-scroll-target="#contingency-tables">1.1. Contingency tables</a></li>
  <li><a href="#box-plots" id="toc-box-plots" class="nav-link" data-scroll-target="#box-plots">1.2. Box plots</a></li>
  </ul></li>
  <li><a href="#exercise-2-is-age-associated-with-social-trust" id="toc-exercise-2-is-age-associated-with-social-trust" class="nav-link" data-scroll-target="#exercise-2-is-age-associated-with-social-trust">Exercise 2: Is <em>age</em> associated with <em>social trust</em>?</a>
  <ul class="collapse">
  <li><a href="#scatterplots" id="toc-scatterplots" class="nav-link" data-scroll-target="#scatterplots">2.1. Scatterplots</a></li>
  </ul></li>
  <li><a href="#exercise-3-is-income-inequality-associated-with-social-trust" id="toc-exercise-3-is-income-inequality-associated-with-social-trust" class="nav-link" data-scroll-target="#exercise-3-is-income-inequality-associated-with-social-trust">Exercise 3: Is <em>income inequality</em> associated with <em>social trust</em>?</a></li>
  <li><a href="#exercise-4-continue-your-analysis-for-assignment-2" id="toc-exercise-4-continue-your-analysis-for-assignment-2" class="nav-link" data-scroll-target="#exercise-4-continue-your-analysis-for-assignment-2">Exercise 4: Continue your analysis for Assignment 2</a></li>
  </ul></li>
  <li><a href="#jasp-solutions" id="toc-jasp-solutions" class="nav-link" data-scroll-target="#jasp-solutions">JASP solutions</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content column-page-left" id="quarto-document-content"><header id="title-block-header" class="quarto-title-block"></header>




<section id="workshop-2-worksheet" class="level1">
<h1>Workshop 2 Worksheet</h1>
<section id="learning-outcomes" class="level2">
<h2 class="anchored" data-anchor-id="learning-outcomes">Learning outcomes</h2>
<p>By the end of the session, you should be familiar with:</p>
<ul>
<li>how to create and interpret cross-tabulations (contingency tables)</li>
<li>how to create some of the most commonly used plots to visually summarise relationships between two or more variables</li>
<li>the basic intuition behind “associations” among variables</li>
</ul>
</section>
<section id="intro" class="level2">
<h2 class="anchored" data-anchor-id="intro">Intro</h2>
<p>We will continue where we left off in the last workshop, completing any exercises that remained unfinished. Then, using some of the same datasets that we downloaded in the last workshop, we tabulate or plot (as appropriate for the given data type) the relationship between the “social trust” variable and some other variables. We will then replicate some of the analyses presented in <span class="citation" data-cites="WilkinsonPickett2010SpiritLevelWhy">Wilkinson and Pickett (<a href="#ref-WilkinsonPickett2010SpiritLevelWhy" role="doc-biblioref">2009</a>)</span> and <span class="citation" data-cites="PickettEtAl2024SpiritLevel15">Pickett, Gauhar, and Wilkinson (<a href="#ref-PickettEtAl2024SpiritLevel15" role="doc-biblioref">2024</a>)</span>, which use data aggregated at national levels to compare the association between <em>social trust</em> and <em>income inequality</em> in a number of economically developed countries.</p>
</section>
<section id="exercise-0-your-module-data-and-analysis-folder" class="level2">
<h2 class="anchored" data-anchor-id="exercise-0-your-module-data-and-analysis-folder">Exercise 0: Your module data and analysis folder</h2>
<p>In Workshop 1 you created a folder for this module on your institutional <strong>OneDrive</strong> storage drive (e.g.&nbsp;C:\<strong>OneDrive - Newcastle University</strong>\SOC2069) and within that a sub-folder called “Data”. You used that sub-folder to save the datasets downloaded as part of the exercises in the Workshop 1 Worksheet. If you did not create this folder in Workshop 1, go back to the <em>Workshop 1 Worksheet</em> and follow the guidance there to set up your folder structure for future use.</p>
</section>
<section id="exercise-1-does-trust-vary-by-sex" class="level2">
<h2 class="anchored" data-anchor-id="exercise-1-does-trust-vary-by-sex">Exercise 1: Does <em>trust</em> vary by <em>sex</em>?</h2>
<p>In <a href="../../Materials/Worksheets/worksheet_w1.html#exercise-1-univariate-descriptive-statistics-using-jasp" target="_blank"><em>Workshop 1 Worksheet - Exercise 1</em></a> we explored univariate distributions (i.e.&nbsp;single variables). In that exercise, we used data from the UK sample of the <em>European Social Survey</em>, Round 11 (<strong>UK-ESS11</strong>). You may have saved your work (and modified dataset) from Workshop 1 as a <code>.jasp</code> file (e.g.&nbsp;“ess11-example.jasp”) as instructed in <a href="../../Materials/Worksheets/worksheet_w1.html#save-your-analysis" target="_blank"><em>Workshop 1 Worksheet - Exercise 1.4</em></a>. If so, you can open that file for this exercise and continue where you left off. Otherwise, follow the instructions in <a href="../../Materials/Worksheets/worksheet_w1.html#exercise-1-univariate-descriptive-statistics-using-jasp" target="_blank"><em>Workshop 1 Worksheet - Exercise 1</em></a> to download the dataset (if needed) and load it into <strong>JASP</strong>.</p>
<p>You can also download the <strong>JASP solution</strong> file for <em>Workshop 1 Worksheet - Exercise 1</em> below:</p>
<p><img src="../../Materials/pics/JASP_logo.png" height="17"> <a href="../../Materials/Worksheets/w1_gb-ess11-trust.jasp">Exercise 1: Descriptive statistics</a></p>
<p>In <em>Workshop 1 Worksheet - Exercise 1</em> we created <strong>descriptive statistics</strong> summaries, <strong>frequency tables</strong> and some basic <strong>distribution plots</strong> for the “social trust”, “sex” and “age” variables in the UK-ESS11. In this exercise, we will check how “social trust” relates to “sex” and “age” by exploring some <strong>bivariate descriptive statistics</strong>.</p>
<p>As we know from the lecture, just as with univariate descriptions, the choice of tabulation and visualisation options depends on the types of variables we are exploring. We begin by describing the relationship between <strong>two categorical variables</strong> using <strong>contingency tables</strong> (also known as <strong>cross-tabulations</strong>). We call them “contingency tables” because they show us the values of one variable <em>contingent on the values of the other</em>, or “cross-tabulations” because we present the frequency distribution of one variable as distributed <em>across</em> the levels of another categorical variable.</p>
<section id="contingency-tables" class="level3">
<h3 class="anchored" data-anchor-id="contingency-tables">1.1. Contingency tables</h3>
<ol type="1">
<li>Open the <code>gb-ess11-trust.sav</code> dataset in JASP. You should now see something like this:</li>
</ol>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="images/paste-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-1"><img src="images/paste-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="649"></a></p>
</figure>
</div>
<ol start="2" type="1">
<li>Identify the following two variables in the dataset: “social trust” and “sex”. We are interested in finding out the distribution of “social trust” among men and women. For this, we will create a <em>contingency table</em>. Use the <strong><em>Frequencies</em></strong> &gt; <strong><em>[Classical] Contingency Tables</em></strong> menu option. Move the “social trust” variable to the <strong><em>Rows</em></strong> field and the “sex” variable to the <strong><em>Columns</em></strong> field. You should be seeing something like this:</li>
</ol>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="images/paste-10.png" class="lightbox" data-gallery="quarto-lightbox-gallery-2"><img src="images/paste-10.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="553"></a></p>
</figure>
</div>
<ol start="3" type="1">
<li>By default we can see the observed counts in each cell of the table. This tells us the exact number of respondents of different sexes in each of their chosen category of the social trust scale. This may be able to tell us something useful in very small tables, but in this case, it is hard to decipher the message. To improve the interpretability of the table, we can change it so that it displays percentages instead of raw counts. To do that, expand the <strong><em>Cells</em></strong> sub-menu and experiment with the options. The best solution in this particular case - to avoid having a too overloaded and complex table - is to untick the “<strong>Observed</strong>” counts box and instead select only “<strong>Column</strong>” Percentages; that will tell us the percentage distribution of responses on the “social trust” scale <em>within each sex group</em>. You should be seeing something like this:</li>
</ol>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="images/paste-11.png" class="lightbox" data-gallery="quarto-lightbox-gallery-3"><img src="images/paste-11.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="495"></a></p>
</figure>
</div>
<ol start="4" type="1">
<li>If we change to - or add <strong>Row</strong> Percentages - , that will tell us the percentage of men and women <em>within each category of the social trust scale</em>. Try that too and think about the difference compared to the previous option.</li>
<li>Interpret the <strong><em>Contingency Tables</em></strong> part of the output (you can hide the <strong><em>Chi-Squared Tests</em></strong> table from the output by un-ticking the <span class="math inline">\(\chi^2\)</span> option under the <strong><em>Statistics</em></strong> sub-menu).</li>
</ol>
<div class="questionblock">
<p><strong>Questions</strong></p>
<ul>
<li>How many women in your dataset answered “You can’t be too careful”?</li>
<li>What percentage of the men in your dataset answered that “Most people can be trusted”?</li>
<li>What percentage of those who answered “Most people can be trusted” are men, and what percentage are women?</li>
<li>Based on your cross-tabulation, do women or men in your dataset have a higher level of “social trust”?</li>
</ul>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-1-contents" aria-controls="callout-1" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Solution
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-1" class="callout-1-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>The full table has 11 rows. These are the parts you need (n = 822 men and 858 women with a valid answer):</p>
<table class="caption-top table">
<colgroup>
<col style="width: 29%">
<col style="width: 10%">
<col style="width: 13%">
<col style="width: 12%">
<col style="width: 15%">
<col style="width: 18%">
</colgroup>
<thead>
<tr class="header">
<th><code>ppltrst</code></th>
<th style="text-align: right;">Men: count</th>
<th style="text-align: right;">Men: column %</th>
<th style="text-align: right;">Women: count</th>
<th style="text-align: right;">Women: column %</th>
<th style="text-align: right;">Row %: men / women</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>0 You can’t be too careful</td>
<td style="text-align: right;">28</td>
<td style="text-align: right;">3.4</td>
<td style="text-align: right;">31</td>
<td style="text-align: right;">3.6</td>
<td style="text-align: right;">47.5 / 52.5</td>
</tr>
<tr class="even">
<td>10 Most people can be trusted</td>
<td style="text-align: right;">17</td>
<td style="text-align: right;">2.1</td>
<td style="text-align: right;">14</td>
<td style="text-align: right;">1.6</td>
<td style="text-align: right;">54.8 / 45.2</td>
</tr>
<tr class="odd">
<td>Answered 6 to 10 (sum of rows)</td>
<td style="text-align: right;">455</td>
<td style="text-align: right;">55.4</td>
<td style="text-align: right;">414</td>
<td style="text-align: right;">48.3</td>
<td style="text-align: right;"></td>
</tr>
</tbody>
</table>
<ul>
<li><strong>31 women</strong> answered “You can’t be too careful” (0).</li>
<li><strong>2.1% of men</strong> answered “Most people can be trusted” (10).</li>
<li>Of the 31 people who answered 10, <strong>54.8% are men and 45.2% are women</strong> (row percentages).</li>
<li><strong>Men are somewhat more trusting</strong>: 55.4% of men but 48.3% of women answered 6 or higher. With 11 answer categories the table is hard to read; a single summary such as this, or the box plot in the next task, makes the comparison clearer.</li>
</ul>
</div>
</div>
</div>
</section>
<section id="box-plots" class="level3">
<h3 class="anchored" data-anchor-id="box-plots">1.2. Box plots</h3>
<p>We have seen last week that the “social trust” variable measured on a 0-10 eleven-point scale is best treated as a “Scale” (i.e.&nbsp;numeric) variable instead of treating it as a “Nominal”/“Ordinal” categorical variable as we have done above; and we know from the lecture that if we want to visualise the relationship between a categorical Nominal variable (like “sex”) and a numeric Scale variable (as the eleven-point social trust measure), the best approach is through a <strong>box plot</strong>, which shows the median, the middle 50% and the spread of trust in each category of the categorical variable (i.e.&nbsp;for “men” and “women” in this case).</p>
<p>To generate a box plot, we return to the descriptive analysis tabs that we are already familiar with:</p>
<ol type="1">
<li><p>Create another new descriptive analysis in your JASP session (<strong><em>Descriptives</em></strong> &gt; <strong><em>Descriptive Statistics</em></strong> menu option), to keep your previous analysis above intact on the output page;</p></li>
<li><p>We will now check the distribution of “social trust” across the two sexes measured in our data. Move the “social trust” variable to the <strong><em>Variables</em></strong> box and the “sex” variable to the <strong><em>Split</em></strong> field.</p></li>
<li><p>You may remember from <em>Workshop 1 Worksheet - Exercise 1</em> that we can manually change the measurement type of our variables for a specific analysis without altering the underlying data more permanently. In this case, we will need to change the type of the “social trust” variable to “Scale”. Click on the measurement type <strong>icon</strong> (not the text label, but the icon), which will bring up the options we see in the image below:</p></li>
</ol>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="images/paste-3.png" class="lightbox" data-gallery="quarto-lightbox-gallery-4"><img src="images/paste-3.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="484"></a></p>
</figure>
</div>
<p>Then, we can change the type.</p>
<ol start="4" type="1">
<li>After we make the change to the variable type, we can click on the “<strong>Customizable Plots</strong>” option set in the left panel and tick the “<strong>Boxplots</strong>” option. You should be seeing something like this:</li>
</ol>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="images/paste-12.png" class="lightbox" data-gallery="quarto-lightbox-gallery-5"><img src="images/paste-12.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="578"></a></p>
</figure>
</div>
<ol start="5" type="1">
<li>If needed, we can <strong>resize the output graph by hovering over the plot and dragging out the bottom-right corner</strong>.</li>
</ol>
<div class="questionblock">
<p><strong>Questions</strong></p>
<ul>
<li>What is the box plot telling us? Note down everything that comes to your mind. How does the boxplot visualise the information displayed in the “Descriptive statistics” table above? You can use the lecture slides to remind yourself of the information contained in box plots.</li>
</ul>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-2-contents" aria-controls="callout-2" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Solution
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-2" class="callout-2-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<table class="caption-top table">
<thead>
<tr class="header">
<th><code>ppltrst</code> (Scale)</th>
<th style="text-align: right;">Men</th>
<th style="text-align: right;">Women</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Valid</td>
<td style="text-align: right;">822</td>
<td style="text-align: right;">858</td>
</tr>
<tr class="even">
<td>Mean</td>
<td style="text-align: right;">5.54</td>
<td style="text-align: right;">5.27</td>
</tr>
<tr class="odd">
<td>Median</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">5</td>
</tr>
<tr class="even">
<td>Standard deviation</td>
<td style="text-align: right;">2.24</td>
<td style="text-align: right;">2.34</td>
</tr>
<tr class="odd">
<td>25th percentile</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">4</td>
</tr>
<tr class="even">
<td>75th percentile</td>
<td style="text-align: right;">7</td>
<td style="text-align: right;">7</td>
</tr>
<tr class="odd">
<td>Minimum, maximum</td>
<td style="text-align: right;">0, 10</td>
<td style="text-align: right;">0, 10</td>
</tr>
</tbody>
</table>
<ul>
<li><strong>The line inside each box is the median</strong>: 6 for men, 5 for women.</li>
<li><strong>The box covers the middle 50%</strong> of respondents (the interquartile range): from 4 to 7 for both sexes, so the boxes overlap completely.</li>
<li><strong>The whiskers</strong> reach the most extreme answers within 1.5 × IQR of the box. Here that covers the whole 0-10 scale, so there are no outliers.</li>
<li><strong>Reading it together with the table</strong>: men score slightly higher on average (a gap of 0.27 points in the means, one point in the medians), but the two distributions are very similar. The gap between the groups is small compared with the spread within each group (an SD of about 2.3).</li>
</ul>
</div>
</div>
</div>
</section>
</section>
<section id="exercise-2-is-age-associated-with-social-trust" class="level2">
<h2 class="anchored" data-anchor-id="exercise-2-is-age-associated-with-social-trust">Exercise 2: Is <em>age</em> associated with <em>social trust</em>?</h2>
<p>In this exercise we will be using the same dataset as in the previous exercise, but we will explore the association between “age” and “social trust”. If we treat our measurement of “social trust” as a Scale measurement, then this means that we are exploring the relationship between two Scale-type variables; you may remember from the lecture slides that the appropriate visual analysis tool in this case is a <strong>scatterplot</strong>.</p>
<section id="scatterplots" class="level3">
<h3 class="anchored" data-anchor-id="scatterplots">2.1. Scatterplots</h3>
<p>In JASP, we can generate basic scatterplots using the already familiar descriptive analysis menu options:</p>
<ol type="1">
<li>Create a new descriptive analysis in your JASP session (<strong><em>Descriptives</em></strong> &gt; <strong><em>Descriptive Statistics</em></strong> menu option). This will keep the outputs you created earlier in your JASP analysis workbook and append the new analysis underneath.</li>
<li>Move the two variables of interest over to the <strong><em>Variables</em></strong> box (both of them in the same box);</li>
<li>Change the type of the “social trust” variable to Scale, as you have done in the previous analysis;</li>
<li>Expand the <strong><em>Customizable plots</em></strong> option and tick <strong><em>Scatter plots;</em></strong></li>
<li>You can play around with the options under <strong><em>Scatter plots</em></strong> to simplify the plot (e.g.&nbsp;remove the univariate distributions of the variables displayed on the margins/changed them to histograms, remove the regression line, etc.). You can also manually increase the size of the plot by dragging the bottom-right corner.</li>
</ol>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Beware
</div>
</div>
<div class="callout-body-container callout-body">
<p>The order in which you list the variables in the “Variables” field matters: the variable listed first will appear on the X axis, and the variable listed second will appear on the Y axis. You can manually reorder the variables in the list by dragging them. Try changing the order of the two variables.</p>
</div>
</div>
<p>You should be seeing something like this:</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="images/paste-13.png" class="lightbox" data-gallery="quarto-lightbox-gallery-6"><img src="images/paste-13.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="536"></a></p>
</figure>
</div>
<div class="questionblock">
<p><strong>Questions</strong></p>
<ul>
<li>What is the scatter plot telling us? Note down everything that comes to your mind.</li>
<li>What happens if you add the <code>gndr</code> variable to the <strong><em>Split</em></strong> box?
<ul>
<li>Try to interpret what this tri-variate relationship is telling us (the <em>Descriptive Statistics</em> table is probably more useful here)</li>
</ul></li>
</ul>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-4-contents" aria-controls="callout-4" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Solution
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-4" class="callout-4-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ul>
<li><strong>Overplotting</strong>: because trust takes only 11 values and age only whole years, many respondents sit on exactly the same point, so the scatter plot looks like rows of dots. The density plots on the margins (or histograms) help show where most respondents are.</li>
<li><strong>Almost no linear association</strong>: the regression line rises only very slightly. The correlation between age and trust is <strong>r = 0.05</strong> (n = 1,643 with valid answers on both), and the slope is about 0.006 points of trust per year of age: 0.06 points per decade, or about a third of a point between age 20 and age 75.</li>
<li><strong>Split by <code>gndr</code></strong>: the pattern is equally flat for men (r = 0.04) and women (r = 0.06). The <em>Descriptive Statistics</em> table shows the more useful information: men and women in the sample have a similar average age (53.8 and 53.4) but men report slightly higher average trust (5.54 vs 5.32 among those with a valid age). Both associations are small: about a third of a point between age 20 and age 75, and about a quarter of a point between men and women, on a scale whose standard deviation is 2.3.</li>
<li><strong>Compare with other surveys</strong>: in the much larger Community Life Survey and Citizenship Survey (Workshop 4), trust does rise with age. A weak association in one sample of 1,600 people is not proof that there is none.</li>
</ul>
</div>
</div>
</div>
</section>
</section>
<section id="exercise-3-is-income-inequality-associated-with-social-trust" class="level2">
<h2 class="anchored" data-anchor-id="exercise-3-is-income-inequality-associated-with-social-trust">Exercise 3: Is <em>income inequality</em> associated with <em>social trust</em>?</h2>
<p>For this exercise, go to the <a href="../../Data/index.html">Data</a> site and roll down the section on <i class="fa-solid fa-database" aria-label="database"></i> <strong>Trust &amp; Inequality</strong>.</p>
<p>The lecture has already introduced the 2009 book <em>The Spirit Level</em> by <span class="citation" data-cites="WilkinsonPickett2010SpiritLevelWhy">Wilkinson and Pickett (<a href="#ref-WilkinsonPickett2010SpiritLevelWhy" role="doc-biblioref">2009</a>)</span>. There, they argued that the level of income inequality in the most economically developed countries is correlated with a number of social problems, reduced levels of <em>social trust</em> among them. They updated their analysis fifteen years later <span class="citation" data-cites="PickettEtAl2024SpiritLevel15">(<a href="#ref-PickettEtAl2024SpiritLevel15" role="doc-biblioref">Pickett et al. 2024</a>)</span>. Datasets related to their analyses can be downloaded from the <a href="../../Data/index.html">Data</a> site. The two datasets available there allow us to replicate the analysis of the relationship between <em>income inequality</em> and <em>social trust</em> summarised in <em>Figure 4.1</em> (Chapter 4: “Community life and social relations”, pp.&nbsp;49-62) of <span class="citation" data-cites="WilkinsonPickett2010SpiritLevelWhy">Wilkinson and Pickett (<a href="#ref-WilkinsonPickett2010SpiritLevelWhy" role="doc-biblioref">2009</a>)</span> and <em>Figure 7</em> (page 16) in <span class="citation" data-cites="PickettEtAl2024SpiritLevel15">Pickett et al. (<a href="#ref-PickettEtAl2024SpiritLevel15" role="doc-biblioref">2024</a>)</span> (see also <span class="citation" data-cites="Pickett2024SpiritLevel15TechAppendix">Pickett (<a href="#ref-Pickett2024SpiritLevel15TechAppendix" role="doc-biblioref">2024</a>)</span>). You can <a href="../../Data/workshop_data/w2/codebook_pickett.html#income-inequality">read more about the measurement of <em>income inequality</em> here</a>.</p>
<ol type="1">
<li><p>Download the datasets to your <strong><em>Data</em></strong> (sub)folder and open them in JASP;</p></li>
<li><p>Create summary descriptive statistics for all the variables in the dataset (<strong><em>Descriptives</em></strong> &gt; <strong><em>Descriptive Statistics</em></strong> menu option).</p></li>
</ol>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Tip
</div>
</div>
<div class="callout-body-container callout-body">
<p>Because there are only a few variables in the dataset, you can select them all by clicking one of them, then <code>Ctrl + A</code>, and moving them all over to the <strong><em>Variables</em></strong> box</p>
</div>
</div>
<ol start="3" type="1">
<li><p>Visualise the relationship between “income inequality” and “social trust” using the steps practiced in the previous exercise.</p></li>
<li><p>We can use these datasets to play around with some more advanced visualisation options to reproduce the published figures. It would require too much detail to give step-by-step instructions on how to do this, but you can download two worked-out JASP worksheets and check through all the options:</p></li>
</ol>
<p><img src="../../Materials/pics/JASP_logo.png" height="17"> <a href="../../Materials/Worksheets/w2_pickett2009.jasp">Exercise 3a: Reproducing Figure 4.1 in Wilkinson &amp; Pickett (2009)</a></p>
<p><img src="../../Materials/pics/JASP_logo.png" height="17"> <a href="../../Materials/Worksheets/w2_pickett&amp;al2024.jasp">Exercise 3b: Reproducing Figure 7 in Pickett &amp; al.&nbsp;(2024)</a></p>
<ol start="5" type="1">
<li>Finally, request the <strong>correlation</strong> between income inequality and trust in both datasets (<strong><em>Regression</em></strong> &gt; <strong><em>Correlation</em></strong>). In the 2024 dataset there are two measures of inequality: try both.</li>
</ol>
<div class="questionblock">
<p><strong>Questions</strong></p>
<ul>
<li>How many countries are in each dataset? Which countries have the lowest and the highest trust and inequality in the 2009 data?</li>
<li>Describe the association in the 2009 data in one sentence: direction, strength, and any countries that don’t fit the pattern.</li>
<li>How strong is the association in the 2024 data, with each measure of inequality? Look at the scatter plot: can you see why the two measures give such different correlations?</li>
<li>What can, and can’t, these country-level data tell us about whether <em>individuals</em> with lower incomes trust less?</li>
</ul>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-6-contents" aria-controls="callout-6" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Solution
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-6" class="callout-6-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ul>
<li><strong>2009 data</strong> (<code>pickett2009</code>): <strong>23</strong> rich countries. Trust ranges from <strong>10.0%</strong> (Portugal) to <strong>66.5%</strong> (Denmark); income inequality (the ratio of the income of the richest fifth to that of the poorest fifth) from <strong>3.4</strong> (Japan) to <strong>9.7</strong> (Singapore).</li>
<li><strong>The association</strong>: more unequal countries tend to have lower trust, and the association is strong (<strong>r = −0.66</strong>). There are clear exceptions: France (with middling inequality, 5.6) and Belgium (with low inequality, 4.6) have much lower trust (22% and 31%) than countries with similar inequality, while the USA and New Zealand trust more than their high inequality would suggest.</li>
<li><strong>2024 data</strong> (<code>pickett&amp;al2024</code>): <strong>43</strong> countries, now including several middle-income countries. The correlation is <strong>r = −0.43</strong> with the Gini coefficient but only <strong>r = −0.15</strong> with the quintile ratio. The scatter plot shows why: China combines by far the highest measured quintile ratio (28) with high measured trust (65%). That single case flattens the line. Without China, both correlations are about <strong>−0.6</strong>. One unusual case can change a correlation a lot, so always look at the plot before you trust the number.</li>
<li><strong>Country level vs individual level</strong>: these data describe countries, not people. They show that unequal <em>countries</em> tend to be less trusting, but they cannot tell us whether poorer <em>individuals</em> within those countries trust less. Drawing individual-level conclusions from group-level data is the <em>ecological fallacy</em>. To study individuals we need individual-level survey data, as in Exercises 1 and 2.</li>
</ul>
</div>
</div>
</div>
</section>
<section id="exercise-4-continue-your-analysis-for-assignment-2" class="level2">
<h2 class="anchored" data-anchor-id="exercise-4-continue-your-analysis-for-assignment-2">Exercise 4: Continue your analysis for Assignment 2</h2>
<p>Building on the work you have done in <a href="../../Materials/Worksheets/worksheet_w1.html" target="_blank"><em>Workshop 1 Worksheet - Exercise 3</em></a>, open the dataset you have used to address one of the questions below.</p>
<ol type="1">
<li><p>Identify (the) two main variables relevant to the question, perform univariate descriptive statistics, and check their relationship using one of the plots/tabulations practised in the previous exercises above.</p></li>
<li><p>Select some other variables of different types and check their association with your main <em>dependent</em> variable using the plots/tabulations practised in the previous exercises above.</p></li>
</ol>
<p>Reminder of the research questions to choose from to address in Assignment 2:</p>
<ol type="A">
<li>Are religious people more satisfied with life?</li>
<li>Are older people more likely to see the death penalty as justifiable?</li>
<li>What factors are associated with opinions about future European Union enlargement among Europeans?</li>
<li>Is higher internet use associated with stronger anti-immigrant sentiments?</li>
<li>How does victimisation relate to trust in the police?</li>
<li>What factors are associated with belief in life after death?</li>
<li>Are government/public sector employees more inclined to perceive higher levels of corruption than those working in the private sector?</li>
</ol>
<p>For now, choose one question that you find most sympathetic (you don’t need to stick with it for the assignment, but you could if you wanted to!). All of the questions can be answered with at least one of the survey datasets that you downloaded (the “WVS7” or “ESS10”) and often they both contain relevant variables.</p>
</section>
</section>
<section id="jasp-solutions" class="level1">
<h1>JASP solutions</h1>
<p>Below you can download JASP files with solutions to some of the exercises in this worksheet:</p>
<p><img src="../../Materials/pics/JASP_logo.png" height="17"> <a href="../../Materials/Worksheets/w2_gb-ess11-trust.jasp">Exercise 1</a></p>



</section>

<div id="quarto-appendix" class="default"><section class="quarto-appendix-contents" role="doc-bibliography" id="quarto-bibliography"><h2 class="anchored quarto-appendix-heading">References</h2><div id="refs" class="references csl-bib-body hanging-indent" role="list">
<div id="ref-Pickett2024SpiritLevel15TechAppendix" class="csl-entry" role="listitem">
Pickett, Kate. 2024. <em><a href="https://media.equality-trust.out.re/uploads/2024/07/Technical-Appendix-20-07.pdf">The <span>Spirit Level</span> at 15 – <span>Technical Appendix</span></a></em>. London: The Equality Trust.
</div>
<div id="ref-PickettEtAl2024SpiritLevel15" class="csl-entry" role="listitem">
Pickett, Kate, Aini Gauhar, and Richard Wilkinson. 2024. <em><a href="https://media.equality-trust.out.re/uploads/2024/07/The-Spirit-Level-at-15-2024-FINAL.pdf">The <span>Spirit Level</span> at 15: <span>The Enduring Impact</span> of <span>Inequality</span></a></em>. <em>Monograph</em>. London: The Equality Trust.
</div>
<div id="ref-WilkinsonPickett2010SpiritLevelWhy" class="csl-entry" role="listitem">
Wilkinson, Richard G., and Kate Pickett. 2009. <em>The Spirit Level: Why Greater Equality Makes Societies Stronger</em>. <span>London</span>: <span>Allen Lane</span>.
</div>
</div></section></div></main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
            // target, if specified
            link.setAttribute("target", "_blank");
            if (link.getAttribute("rel") === null) {
              link.setAttribute("rel", "noopener");
            }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->
<script>var lightboxQuarto = GLightbox({"closeEffect":"zoom","descPosition":"bottom","loop":false,"openEffect":"zoom","selector":".lightbox"});
(function() {
  let previousOnload = window.onload;
  window.onload = () => {
    if (previousOnload) {
      previousOnload();
    }
    lightboxQuarto.on('slide_before_load', (data) => {
      const { slideIndex, slideNode, slideConfig, player, trigger } = data;
      const href = trigger.getAttribute('href');
      if (href !== null) {
        const imgEl = window.document.querySelector(`a[href="${href}"] img`);
        if (imgEl !== null) {
          const srcAttr = imgEl.getAttribute("src");
          if (srcAttr && srcAttr.startsWith("data:")) {
            slideConfig.href = srcAttr;
          }
        }
      } 
    });
  
    lightboxQuarto.on('slide_after_load', (data) => {
      const { slideIndex, slideNode, slideConfig, player, trigger } = data;
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(slideNode);
      }
    });
  
  };
  
})();
          </script>




</body></html>