<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.18">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>SOC2069 | 2026</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<link href="../../site_pics/logo_name_white.jpg" rel="icon" type="image/jpeg">
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-64a204ab8560d761af7679ceaba22944.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-1e062f3de27d5a13a642256a90a2a83c.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<link href="../../site_libs/quarto-contrib/fontawesome6-0.1.0/all.css" rel="stylesheet">
<link href="../../site_libs/quarto-contrib/fontawesome6-0.1.0/latex-fontsize.css" rel="stylesheet">
<script src="../../site_libs/quarto-contrib/iconify-2.1.0/iconify-icon.min.js"></script>
<script src="../../site_libs/quarto-contrib/glightbox/glightbox.min.js"></script>
<link href="../../site_libs/quarto-contrib/glightbox/glightbox.min.css" rel="stylesheet">
<link href="../../site_libs/quarto-contrib/glightbox/lightbox.css" rel="stylesheet">
<script id="quarto-search-options" type="application/json">{
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@4/tex-chtml.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../labcss.css">
</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title"><strong>SOC2069</strong> <i class="fa-solid fa-chart-line" aria-label="chart-line"></i> Quantitative Methods</span>
    </a>
  </div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../Materials/index.html"> 
<span class="menu-text">Materials</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../Data/index.html"> 
<span class="menu-text">Data</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="https://ncl.instructure.com/courses/73213" target="_blank"> 
<span class="menu-text"><iconify-icon role="img" inline="" icon="arcticons:canvasstudent" style="font-size: l;" aria-label="Icon canvasstudent from arcticons Iconify.design set." title="Icon canvasstudent from arcticons Iconify.design set."></iconify-icon> Canvas</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-full page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#workshop-5-worksheet" id="toc-workshop-5-worksheet" class="nav-link active" data-scroll-target="#workshop-5-worksheet">Workshop 5 Worksheet</a>
  <ul class="collapse">
  <li><a href="#learning-outcomes" id="toc-learning-outcomes" class="nav-link" data-scroll-target="#learning-outcomes">Learning outcomes</a></li>
  <li><a href="#intro" id="toc-intro" class="nav-link" data-scroll-target="#intro">Intro</a></li>
  <li><a href="#exercise-5.1-interpreting-inferential-statistics" id="toc-exercise-5.1-interpreting-inferential-statistics" class="nav-link" data-scroll-target="#exercise-5.1-interpreting-inferential-statistics">Exercise 5.1: Interpreting inferential statistics</a></li>
  <li><a href="#exercise-5.2-how-sure-can-we-be-about-the-share-who-trust" id="toc-exercise-5.2-how-sure-can-we-be-about-the-share-who-trust" class="nav-link" data-scroll-target="#exercise-5.2-how-sure-can-we-be-about-the-share-who-trust">Exercise 5.2: How sure can we be about the share who trust?</a></li>
  <li><a href="#exercise-5.3-do-men-and-women-differ-in-trust" id="toc-exercise-5.3-do-men-and-women-differ-in-trust" class="nav-link" data-scroll-target="#exercise-5.3-do-men-and-women-differ-in-trust">Exercise 5.3: Do men and women differ in trust?</a></li>
  <li><a href="#exercise-5.4-the-same-question-different-precision" id="toc-exercise-5.4-the-same-question-different-precision" class="nav-link" data-scroll-target="#exercise-5.4-the-same-question-different-precision">Exercise 5.4: The same question, different precision</a></li>
  <li><a href="#exercise-5.5-confidence-intervals-for-odds-ratios" id="toc-exercise-5.5-confidence-intervals-for-odds-ratios" class="nav-link" data-scroll-target="#exercise-5.5-confidence-intervals-for-odds-ratios">Exercise 5.5: Confidence intervals for odds ratios</a></li>
  <li><a href="#exercise-5.6.-complete-your-analysis-for-assignment-2" id="toc-exercise-5.6.-complete-your-analysis-for-assignment-2" class="nav-link" data-scroll-target="#exercise-5.6.-complete-your-analysis-for-assignment-2">Exercise 5.6. Complete your analysis for Assignment 1</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content column-page-left" id="quarto-document-content"><header id="title-block-header" class="quarto-title-block"></header>




<section id="workshop-5-worksheet" class="level1">
<h1>Workshop 5 Worksheet</h1>
<section id="learning-outcomes" class="level2">
<h2 class="anchored" data-anchor-id="learning-outcomes">Learning outcomes</h2>
<p>By the end of the session, you should:</p>
<ul>
<li>gain practice interpreting inferential statistics in regression outputs</li>
<li>calculate and interpret confidence intervals and p-values for a proportion, a difference in means, and regression coefficients in JASP</li>
<li>understand how sample size affects the precision of an estimate</li>
<li>progress with the analysis required for your chosen assignment question</li>
</ul>
</section>
<section id="intro" class="level2">
<h2 class="anchored" data-anchor-id="intro">Intro</h2>
<p>So far, in all previous exercises, we paid almost exclusive attention to obtaining “point estimates” for our independent (explanatory, predictor) variables. These “point estimates” tell us the average and constant effect that a one-unit change in the predictors have on the outcome (dependent) variable, and do so with seemingly unashamed confidence, despite the fact that, as we have seen in some cases (e.g.&nbsp;Portugal’s <code>trust</code> score), they predict individual data points rather poorly.</p>
<p>In Exercise 3.2 we addressed the research question “How is <em>income inequality</em> (at national level) associated with <em>social trust</em> when we adjust for the potential influence of <em>homicide rates</em>?”, but we focused almost exclusively on interpreting the coefficient estimates we obtained for the two predictor variables (<span class="math inline">\(-7.147\)</span> for <code>Income inequality</code> and <span class="math inline">\(0.174\)</span> for <code>Homicides</code>). You should by now be able to confidently interpret these coefficients; if not, you can return to and consult the detailed explanation given in <em>Exercises 3.1-3</em>.</p>
<p>But we did not focus at all on some of the other statistics from these models, which could tell us more about how variable (i.e.&nbsp;precise) these estimates are, and what is the probability that these coefficients obtained from relatively small samples can tell us something reliable about the associations/effects we should find in the whole true population from which these samples were drawn?</p>
<p>We are already given two of these in the standard default output in the columns <strong><em>“Standard Error”</em></strong> and <strong><em>“p”</em></strong>. Another useful such statistic – which relates to both of the previously mentioned ones and is often a more descriptive option –, is the <strong><em>“95% Confidence Intervals”</em></strong>, which is not shown by default but can be requested in the <strong>Statistics</strong> drop-down options set:</p>
<div id="fig-CI" class="quarto-layout-panel">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-CI-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 17.8%;justify-content: center;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="images/Screenshot 2025-12-06 161145.png" class="lightbox" data-gallery="quarto-lightbox-gallery-1" title="Figure&nbsp;1: Multiple linear regression in JASP (including 95% Confidence Intervals)"><img src="images/Screenshot 2025-12-06 161145.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="136"></a></p>
</figure>
</div>
</div>
<div class="quarto-layout-cell" style="flex-basis: 82.2%;justify-content: center;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="images/Screenshot 2025-12-06 161242.png" class="lightbox" data-gallery="quarto-lightbox-gallery-2" title="Figure&nbsp;1: Multiple linear regression in JASP (including 95% Confidence Intervals)"><img src="images/Screenshot 2025-12-06 161242.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="629"></a></p>
</figure>
</div>
</div>
</div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-CI-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1: Multiple linear regression in JASP (including 95% Confidence Intervals)
</figcaption>
</figure>
</div>
<p>Similarly, in Exercise 4.1.1 we addressed the research question <em>How did sex-adjusted age shape social trust in Britain in 2010-2011?</em> using the 2010 British Social Attitudes survey (<code>gb-bsa10-trust.sav</code>), and we fit a logistic regression model that estimated the effect of <code>Age</code> to be <span class="math inline">\(0.006\)</span> “log-odds” (an odds ratio of <span class="math inline">\(1.006\)</span> ) and the effect of being a woman as opposed to being a man (<code>Sex (Female)</code>) to be <span class="math inline">\(-0.437\)</span> “log-odds” (an odds ratio of <span class="math inline">\(0.646\)</span>). We also plotted these estimates/coefficients on the probability scale to get a more intuitive understanding of what they actually mean. You should by now be able to interpret these coefficients with some confidence; if not, you can return to and consult the detailed explanation given in <em>Exercise 4.1.1</em>. Again, however, we did not focus at all on the statistics shown in the <strong><em>“Standard Error”</em></strong> and <strong><em>“p”</em></strong> columns. We can also request the <strong><em>“95% Confidence Interval”</em></strong> in the <strong>Statistics</strong> drop-down options set, just like in the case of linear regression; for logistic regression we also have the option to request the confidence intervals for either the “<strong>Estimate</strong>” (i.e.&nbsp;the point estimate, similar to what in the case of linear regression in labelled by JASP as the “<strong>Unstandardized</strong>” coefficient) or for the “<strong>Odds Ratio</strong>”:</p>
<div id="fig-CI-2" class="quarto-layout-panel">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-CI-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 19.5%;justify-content: center;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="images/Screenshot 2025-12-08 095330.png" class="lightbox" data-gallery="quarto-lightbox-gallery-3" title="Figure&nbsp;2: Multiple logistic regression in JASP (including 95% Confidence Intervals)"><img src="images/Screenshot 2025-12-08 095330.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="166"></a></p>
</figure>
</div>
</div>
<div class="quarto-layout-cell" style="flex-basis: 80.5%;justify-content: center;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="images/Screenshot 2025-12-08 095445.png" class="lightbox" data-gallery="quarto-lightbox-gallery-4" title="Figure&nbsp;2: Multiple logistic regression in JASP (including 95% Confidence Intervals)"><img src="images/Screenshot 2025-12-08 095445.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="684"></a></p>
</figure>
</div>
</div>
</div>
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 20.6%;justify-content: center;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="images/Screenshot 2025-12-08 095525.png" class="lightbox" data-gallery="quarto-lightbox-gallery-5" title="Figure&nbsp;2: Multiple logistic regression in JASP (including 95% Confidence Intervals)"><img src="images/Screenshot 2025-12-08 095525.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="167"></a></p>
</figure>
</div>
</div>
<div class="quarto-layout-cell" style="flex-basis: 79.4%;justify-content: center;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="images/Screenshot 2025-12-08 095602.png" class="lightbox" data-gallery="quarto-lightbox-gallery-6" title="Figure&nbsp;2: Multiple logistic regression in JASP (including 95% Confidence Intervals)"><img src="images/Screenshot 2025-12-08 095602.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="643"></a></p>
</figure>
</div>
</div>
</div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-CI-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2: Multiple logistic regression in JASP (including 95% Confidence Intervals)
</figcaption>
</figure>
</div>
<p>Which of the options we prefer will depend on which of the two we prefer to interpret in more detail in writing; as we discussed, neither are particularly intuitive for human brains, but often the Odds Ratio can provide a clearer interpretation as a <em>percentage change</em> in the <em>odds</em> of being in the indicator outcome category (the one coded as “1”) as opposed to being in the other - reference - category. So you will often see results reported in Odds Ratios in publish articles.</p>
</section>
<section id="exercise-5.1-interpreting-inferential-statistics" class="level2">
<h2 class="anchored" data-anchor-id="exercise-5.1-interpreting-inferential-statistics">Exercise 5.1: Interpreting inferential statistics</h2>
<p>This first exercise is purely conceptual: focus on these statistics relating to the <em>precision</em> and the <em>inferential reliability</em> of the estimates obtained from the two multiple regression models above and try to interpret them in writing.</p>
<div class="questionblock">
<p><strong>Questions</strong></p>
<ul>
<li>Using the lecture slides and the assigned readings, interpret the results focusing on the meaning of the “Standard Error”, “95% CI” and “p” columns</li>
</ul>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Solution: bringing it all together
</div>
</div>
<div class="callout-body-container callout-body">
<p>Once we have thought about the <em>precision</em> and the <em>inferential reliability</em> of the estimates obtained from our models, we can summarise our statistical findings concisely. We could describe our findings in these words:</p>
<blockquote class="blockquote">
<p>As we can see in <a href="#fig-CI" class="quarto-xref">Figure&nbsp;1</a>, a multiple linear regression model has shown that while adjusting for the level of <code>Homicides</code> in a given country, <code>Income inequality</code> is negatively associated with <code>Trust</code>. The model estimates that a one-unit increase in <code>Income inequality</code> is associated with a <span class="math inline">\(7.147\)</span>-point average <em>decrease</em> in social trust as measured on the <code>Trust</code> scale. This estimate can be taken as statistically significant (p-value <span class="math inline">\(&lt; 0.001\)</span>), with a 95% Confidence Interval ranging from <span class="math inline">\(-11\)</span> to <span class="math inline">\(-3.3\)</span>. The rate of <code>Homicides</code>, however, proved <u>not to be</u> a statistically significant predictor of <code>Trust</code> (<span class="math inline">\(p=0.483\)</span>, <span class="math inline">\(\text{95% CI}=-0.33 \text{ to } 0.68\)</span>) when adjusting for the effect of <code>Income inequality</code>.</p>
</blockquote>
<p>Or:</p>
<blockquote class="blockquote">
<p>We fit a multiple logistic regression model to estimate how <code>Age</code> and <code>Sex</code> are associated with trust. The results are shown in <a href="#fig-CI-2" class="quarto-xref">Figure&nbsp;2</a>. We find that, whilst adjusting for <code>Sex</code>, a positive difference of one year in one’s <code>Age</code> is associated with <span class="math inline">\(0.6\%\)</span> higher <em>odds</em> of thinking that “most people can be trusted”. However, the 95% Confidence Interval for the odds ratio runs from <span class="math inline">\(0.9995\)</span> to <span class="math inline">\(1.013\)</span> (JASP rounds the lower bound to <span class="math inline">\(1.000\)</span>), i.e.&nbsp;from a tiny decrease to a <span class="math inline">\(1.3\%\)</span> increase in the odds per year. Because it includes 1 (no difference), we cannot rule out that there is no association between age and trust in the population, which is confirmed by the p-value of <span class="math inline">\(0.07\)</span>. The data are compatible both with no association and with a small positive one, so this sample cannot tell us whether older people in the wider population are more likely to trust. On the other hand, being a female - as opposed to being a male - is statistically significantly (<span class="math inline">\(p&lt;0.001\)</span>) associated with a <span class="math inline">\(35.4\%\)</span> <em>decrease</em> in the odds of thinking that “most people can be trusted” (OR = <span class="math inline">\(0.646\)</span>, 95% CI = <span class="math inline">\(0.505\)</span> to <span class="math inline">\(0.825\)</span>). Put differently, men have a higher probability of trusting others than women do, when adjusting for <code>Age</code>.</p>
</blockquote>
</div>
</div>
</section>
<section id="exercise-5.2-how-sure-can-we-be-about-the-share-who-trust" class="level2">
<h2 class="anchored" data-anchor-id="exercise-5.2-how-sure-can-we-be-about-the-share-who-trust">Exercise 5.2: How sure can we be about the share who trust?</h2>
<p><code>About 15 minutes</code></p>
<p>In the 2010 British Social Attitudes survey, 481 of the 1,060 respondents with a valid answer said that “most people can be trusted” (Workshop 4, Exercise 4.1.1). What can we say about all adults in Britain?</p>
<p>Open your cleaned <code>gb-bsa10-trust</code> JASP file from Workshop 4 (with “Don’t know” and “Refusal” set as missing in <code>SocTrust</code>), or download the solution file at the end of the Workshop 4 worksheet.</p>
<ol type="1">
<li>Go to <strong><em>Frequencies &gt; Binomial Test</em></strong> and move <code>SocTrust</code> to the <strong>Variables</strong> box.</li>
<li>Leave the <strong>Test value</strong> at 0.5: we are testing the null hypothesis that exactly half of the population trusts most people.</li>
<li>Under <strong>Additional Statistics</strong>, tick <strong>Confidence interval</strong> (95%).</li>
</ol>
<div class="questionblock">
<p><strong>Questions</strong></p>
<ul>
<li>What proportion of respondents say “most people can be trusted”? What is the 95% confidence interval for this proportion?</li>
<li>Interpret the interval in a sentence about the population.</li>
<li>What does the p-value tell you about the null hypothesis that exactly half of British adults trust most people?</li>
<li>Check the interval by hand, using the formula from the lecture: <span class="math inline">\(p \pm 1.96 \times \sqrt{p(1-p)/n}\)</span>. How close is it to JASP’s?</li>
</ul>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-2-contents" aria-controls="callout-2" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Solution
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-2" class="callout-2-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ul>
<li><strong>Proportion</strong>: 481 / 1,060 = <strong>0.454</strong> (45.4%). JASP’s 95% CI is <strong>0.423 to 0.484</strong>.</li>
<li><strong>In words</strong>: we can be 95% confident that between about 42% and 48% of adults in Britain in 2010 would have said that most people can be trusted.</li>
<li><strong>The test</strong>: p = <strong>.003</strong>. If exactly half of the population trusted most people, a sample result at least this far from 50% would occur in only about 3 in 1,000 samples. We can reject the null hypothesis: fewer than half of British adults said most people can be trusted. The confidence interval tells the same story: it lies entirely below 0.5.</li>
<li><strong>By hand</strong>: <span class="math inline">\(SE = \sqrt{0.454 \times 0.546 / 1060} = 0.0153\)</span>, so the interval is <span class="math inline">\(0.454 \pm 1.96 \times 0.0153\)</span> = <strong>0.424 to 0.484</strong>. This is almost identical to JASP’s interval, which uses an exact method based on the binomial distribution rather than the normal approximation.</li>
</ul>
</div>
</div>
</div>
</section>
<section id="exercise-5.3-do-men-and-women-differ-in-trust" class="level2">
<h2 class="anchored" data-anchor-id="exercise-5.3-do-men-and-women-differ-in-trust">Exercise 5.3: Do men and women differ in trust?</h2>
<p><code>About 20 minutes</code></p>
<p>In Workshop 2 we found that men in the ESS 2023-24 UK sample scored slightly higher on the 0-10 trust scale than women. Is the difference large enough that it is unlikely to be due to sampling chance?</p>
<p>Open <code>gb-ess11-trust.sav</code> (or your <code>.jasp</code> file from Workshop 2).</p>
<ol type="1">
<li>Go to <strong><em>T-Tests &gt; Independent Samples T-Test</em></strong>.</li>
<li>Move <code>ppltrst</code> to <strong>Dependent Variables</strong> and <code>gndr</code> to <strong>Grouping Variable</strong>. (Make sure <code>ppltrst</code> is treated as Scale.)</li>
<li>Under <strong>Additional Statistics</strong>, tick <strong>Location parameter</strong> (the mean difference) with its <strong>Confidence interval</strong>, <strong>Effect size</strong> (Cohen’s d) and <strong>Descriptives</strong>.</li>
<li>Now fit the same comparison as a <strong>linear regression</strong>: <code>ppltrst</code> as the Dependent Variable and <code>gndr</code> as a <strong>Factor</strong>, with <strong>Confidence intervals</strong> ticked under Statistics. Compare the two outputs.</li>
</ol>
<div class="questionblock">
<p><strong>Questions</strong></p>
<ul>
<li>What are the mean trust scores of men and women, and what is the difference between them?</li>
<li>What are the 95% CI and the p-value for the difference? Is the difference statistically significant at the 5% level?</li>
<li>How large is the difference in substantive terms? Use Cohen’s d and compare the difference with the standard deviation.</li>
<li>How does the linear regression output relate to the t-test?</li>
</ul>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-3-contents" aria-controls="callout-3" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Solution
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-3" class="callout-3-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<table class="caption-top table">
<thead>
<tr class="header">
<th><code>ppltrst</code></th>
<th style="text-align: right;">n</th>
<th style="text-align: right;">Mean</th>
<th style="text-align: right;">SD</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Men (1)</td>
<td style="text-align: right;">822</td>
<td style="text-align: right;">5.54</td>
<td style="text-align: right;">2.24</td>
</tr>
<tr class="even">
<td>Women (2)</td>
<td style="text-align: right;">858</td>
<td style="text-align: right;">5.27</td>
<td style="text-align: right;">2.34</td>
</tr>
</tbody>
</table>
<ul>
<li><strong>Difference</strong> (men − women): <strong>0.27</strong> points on the 0-10 scale.</li>
<li><strong>Uncertainty</strong>: 95% CI <strong>0.05 to 0.49</strong>; t(1678) = 2.44, <strong>p = .015</strong>. The interval excludes 0, so the difference is statistically significant at the 5% level: a gap this large would be unusual if men and women in the population had the same average trust.</li>
<li><strong>Size</strong>: Cohen’s d = <strong>0.12</strong>, which is very small. The difference is about a tenth of the standard deviation within each group (about 2.3 points): the two distributions overlap almost completely. <em>Statistically significant</em> does not mean <em>large</em> or <em>important</em>.</li>
<li><strong>Regression</strong>: with <code>gndr</code> as a factor (reference category: Male), the coefficient for <code>gndr (Female)</code> is <strong>−0.27</strong> (95% CI −0.49 to −0.05), with exactly the same t (in absolute value) and p as the t-test. A linear regression with one binary predictor <em>is</em> an independent samples t-test. The intercept (5.54) is the mean for men.</li>
</ul>
</div>
</div>
</div>
</section>
<section id="exercise-5.4-the-same-question-different-precision" class="level2">
<h2 class="anchored" data-anchor-id="exercise-5.4-the-same-question-different-precision">Exercise 5.4: The same question, different precision</h2>
<p><code>About 20 minutes</code></p>
<p>In Workshop 4 (Exercise 4.2) you asked whether young people (16-24) have lower social trust than older adults, using the Community Life Survey 2023-24 (<code>gb-cls23-trust_nm.sav</code>) and the British Social Attitudes Survey 2024 (<code>gb-bsa24-trust.sav</code>). Open your <code>.jasp</code> files from that exercise, with the cleaned and recoded variables.</p>
<ol type="1">
<li>In each dataset, fit a <strong>linear regression</strong> of the 0-10 trust variable on your young/older variable and sex (as Factors).</li>
<li>Under <strong>Statistics</strong>, tick <strong>Confidence intervals</strong>.</li>
</ol>
<div class="questionblock">
<p><strong>Questions</strong></p>
<ul>
<li>In each survey, what is the estimated difference in trust between 16-24-year-olds and those aged 25+, with its 95% CI and p-value?</li>
<li>How many 16-24-year-olds is each estimate based on? How does this relate to the width of the intervals?</li>
<li>The BSA 2024 result is not statistically significant. Does that mean the BSA 2024 <em>contradicts</em> the Community Life Survey?</li>
</ul>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-4-contents" aria-controls="callout-4" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Solution
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-4" class="callout-4-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<table class="caption-top table">
<colgroup>
<col style="width: 34%">
<col style="width: 21%">
<col style="width: 15%">
<col style="width: 6%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th>Young (16-24) vs 25+, adjusted for sex</th>
<th style="text-align: right;">Difference (0-10 scale)</th>
<th>95% CI</th>
<th style="text-align: right;">p</th>
<th style="text-align: right;">n (of whom aged 16-24)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Community Life Survey 2023-24</td>
<td style="text-align: right;">−0.59</td>
<td>−0.65 to −0.53</td>
<td style="text-align: right;">&lt; .001</td>
<td style="text-align: right;">50,706 (5,040)</td>
</tr>
<tr class="even">
<td>British Social Attitudes 2024</td>
<td style="text-align: right;">−0.16</td>
<td>−0.71 to 0.40</td>
<td style="text-align: right;">.579</td>
<td style="text-align: right;">1,453 (78)</td>
</tr>
</tbody>
</table>
<ul>
<li><strong>Precision</strong>: the CLS interval is about 0.12 points wide; the BSA 2024 interval is about 1.1 points wide, roughly nine times wider. The standard error shrinks with the square root of the sample size, and the BSA 2024 has only 78 young respondents compared with 5,040 in the CLS.</li>
<li><strong>No contradiction</strong>: “not statistically significant” means the BSA 2024 does not have enough evidence to rule out no difference. Its interval, from −0.71 to +0.40, includes 0 but also includes the CLS estimate of −0.59. The two surveys are compatible; the BSA 2024 is simply too small to estimate this particular difference precisely. (They also ask the question differently and cover different populations: Great Britain vs England.)</li>
</ul>
</div>
</div>
</div>
</section>
<section id="exercise-5.5-confidence-intervals-for-odds-ratios" class="level2">
<h2 class="anchored" data-anchor-id="exercise-5.5-confidence-intervals-for-odds-ratios">Exercise 5.5: Confidence intervals for odds ratios</h2>
<p><code>About 20 minutes</code></p>
<p>Return to the logistic regression of trust on age and sex in the Citizenship Survey 2010-11 (<code>gb-cs10-trust.sav</code>, Workshop 4, Exercise 4.1.2), with “Depends” set as missing.</p>
<ol type="1">
<li>Under <strong>Statistics</strong>, tick <strong>Confidence intervals</strong> (they are shown on the odds-ratio scale by default).</li>
<li>Compare the results with the same model fitted to the British Social Attitudes 2010 (<a href="#fig-CI-2" class="quarto-xref">Figure&nbsp;2</a> in the introduction to this worksheet).</li>
</ol>
<div class="questionblock">
<p><strong>Questions</strong></p>
<ul>
<li>Which odds ratios have confidence intervals that exclude 1? What does that tell you?</li>
<li>Why are the Citizenship Survey intervals so much narrower than the BSA 2010 ones?</li>
<li>The odds ratio for women is 0.82 in one survey and 0.65 in the other. Are the two surveys’ estimates of the sex difference compatible with each other?</li>
</ul>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-5-contents" aria-controls="callout-5" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Solution
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-5" class="callout-5-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<table class="caption-top table">
<colgroup>
<col style="width: 23%">
<col style="width: 44%">
<col style="width: 31%">
</colgroup>
<thead>
<tr class="header">
<th>Odds ratio (95% CI)</th>
<th>Citizenship Survey 2010-11 (n = 14,797)</th>
<th>BSA 2010 (n = 1,060)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Age (per year)</td>
<td>1.011 (1.009 to 1.013), p &lt; .001</td>
<td>1.006 (0.9995 to 1.013), p = .069</td>
</tr>
<tr class="even">
<td>Sex: female</td>
<td>0.82 (0.77 to 0.87), p &lt; .001</td>
<td>0.65 (0.51 to 0.83), p &lt; .001</td>
</tr>
</tbody>
</table>
<ul>
<li><strong>Excluding 1</strong>: in the Citizenship Survey both intervals exclude 1, so both age and sex are statistically significantly associated with trust. In the BSA 2010 only the sex interval excludes 1; the age interval just includes 1.</li>
<li><strong>Width</strong>: the Citizenship Survey has 14 times as many respondents, so its standard errors are much smaller and its intervals much narrower (for women: 0.77 to 0.87, compared with 0.51 to 0.83).</li>
<li><strong>Compatible?</strong> Yes: the two intervals for women overlap (0.77 to 0.83 lies inside both), so the surveys do not clearly disagree. Both point the same way: women have lower odds of saying that people can be trusted. The BSA estimate is just much less precise.</li>
</ul>
</div>
</div>
</div>
</section>
<section id="exercise-5.6.-complete-your-analysis-for-assignment-2" class="level2">
<h2 class="anchored" data-anchor-id="exercise-5.6.-complete-your-analysis-for-assignment-2">Exercise 5.6. Complete your analysis for Assignment 1</h2>
<p>You will find <a href="https://ncl.instructure.com/courses/68718/pages/assignment-2-quantitative-report-detailed-guide?module_item_id=3890944">a detailed guide for Assignment 1 on Canvas, which outlines all the steps involved in completing the assignment, including the recommended structure of the final report</a></p>
<p>In this exercise, you will focus on the <strong><em>analysis</em></strong> component of the assignment which you can then expand or change if your literature review and interpretation of the results necessitate it.</p>
<p>Once you <strong><em>have</em></strong> <strong><em>chosen your preferred research question</em></strong> from among the listed ones and <strong><em>identified the dataset you will want/need to use</em></strong> to address the question, you can follow the basic steps of the data analysis cycle, which we have also tried to follow in the exercises in the previous two workshops:</p>
<ol type="1">
<li><p><strong>Identify the variables</strong> you want to use and provide some <strong>summary descriptive statistics</strong> for them; (<em>this was the topic of Workshop 1)</em></p></li>
<li><p>Check some more detailed <strong><em>univariate</em></strong> <strong>descriptive tabulations and/or visualisations</strong> of the core variables (at least the <strong>outcome</strong> <strong>variable</strong> and the <strong>main explanatory variable</strong>); <em>(this was the topic of Workshop 1)</em></p></li>
<li><p>Identify and perform any required <strong>data cleaning and transformations</strong> (e.g.&nbsp;rename variables to more human-readable names, set additional missing values, label and recode categories, reverse, centre or standardise scales); <em>(we did variable transformations as part of exercises in Workshops 3 and 4).</em></p></li>
<li><p>Explore some initial <strong><em>bivariate</em></strong> <strong>descriptive</strong> <strong>tabulations and/or visualisations</strong> of the core variables (at least between the <strong>outcome</strong> <strong>variable</strong> and the <strong>main explanatory variable</strong>); <em>(this was the topic of Workshop 2)</em></p>
<p><strong>↺</strong> Identify and perform any additionally required <strong>data cleaning and transformations</strong>, and <strong>return to Step 3</strong></p></li>
<li><p>Fit a <strong>simple <em>bivariate</em> regression model</strong> to test the unadjusted statistical association/relationship between the <strong>outcome variable</strong> and the <strong>main explanatory variable</strong>); <em>(this was the topic of Workshops 3 and 4, depending on which regression method (linear or logistic) your dependent variable requires)</em></p>
<p><strong>↺</strong> Identify and perform any additionally required <strong>data cleaning and transformations</strong>, and <strong>return to Step 3</strong></p></li>
<li><p>Build a <strong><em>multiple</em></strong> <strong>regression model</strong> to test the partial statistical association/relationship between the <strong>outcome variable</strong> and the <strong>main explanatory variable</strong> adjusted for the effect of <strong>a number of other independent/control/explanatory variables</strong>; <em>(this was the topic of Workshops 3 and 4, depending on which regression method (linear or logistic) your dependent variable requires)</em></p>
<p><strong>↺</strong> Identify and perform any additionally required <strong>data cleaning and transformations</strong>, and <strong>return to Step 3</strong></p></li>
<li><p>Provide a comprehensive but concise <strong>statistical interpretation</strong> of the regression results: (a) the direction and strength of the relationships, (b) the explanatory strength of the model, (c) the reliability and generalisability of the model estimates; <em>(this is the topic of this week’s lecture and Exercise 5.1 above).</em></p></li>
</ol>
<p>You will perform these analysis steps in JASP, following which you will:</p>
<ul>
<li><p>write down your interpretation of your results in as much detail as possible (either (or both) In JASP notes and your main Word/Text editor document that you are using to write the main text of the report in; it’s a good idea to start saving your notes and interpretations alongside the analysis and outputs directly in JASP to make your work reproducible, then copy it over and adapt it in your main document;</p></li>
<li><p>Select which outputs (descriptive tables, graphs, statistical output tables) you will want to include in the main text of your report and copy them over from JASP into your Word document/text editor. <strong>To copy and paste outputs from JASP, you can click on the small black down-arrows next to the output and select “Copy”, then paste it into your text editor. (Keep in mind that tables will require some manual improvements in Word/text editor to make the content fit the page well).</strong></p></li>
</ul>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="images/clipboard-2232448579.png" class="lightbox" data-gallery="quarto-lightbox-gallery-7"><img src="images/clipboard-2232448579.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="594"></a></p>
</figure>
</div>
<ul>
<li>Make sure to give a caption/title to your graphs and tables in your report.</li>
<li><strong>Identify the main limitations</strong> of the statistical analysis and discuss how they could be improved with more appropriate measurements and statistical techniques;</li>
<li>Provide a <strong>sociological discussion</strong> of how the statistical results, acknowledging the limitations of the analysis, contribute to addressing the research question.</li>
</ul>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
            // target, if specified
            link.setAttribute("target", "_blank");
            if (link.getAttribute("rel") === null) {
              link.setAttribute("rel", "noopener");
            }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->
<script>var lightboxQuarto = GLightbox({"closeEffect":"zoom","descPosition":"bottom","loop":false,"openEffect":"zoom","selector":".lightbox"});
(function() {
  let previousOnload = window.onload;
  window.onload = () => {
    if (previousOnload) {
      previousOnload();
    }
    lightboxQuarto.on('slide_before_load', (data) => {
      const { slideIndex, slideNode, slideConfig, player, trigger } = data;
      const href = trigger.getAttribute('href');
      if (href !== null) {
        const imgEl = window.document.querySelector(`a[href="${href}"] img`);
        if (imgEl !== null) {
          const srcAttr = imgEl.getAttribute("src");
          if (srcAttr && srcAttr.startsWith("data:")) {
            slideConfig.href = srcAttr;
          }
        }
      } 
    });
  
    lightboxQuarto.on('slide_after_load', (data) => {
      const { slideIndex, slideNode, slideConfig, player, trigger } = data;
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(slideNode);
      }
    });
  
  };
  
})();
          </script>




</body></html>